/**
 * Hand-crafted meditation scripts for the Mindfulness path.
 * Each meditation has speech segments only — pauses are added by the seed script.
 */

import type { MeditationScript } from "../practice-content";

export const MINDFULNESS_CONTENT: Record<
  string,
  Record<string, MeditationScript>
> = {
  // ── Retreat 1: "Arriving Here" (Present moment) ───────────────────

  "Arriving Here": {
    "The Pause": {
      // 10 min — 3 segments
      segments: [
        `Welcome. Right now, in this very breath, you're choosing something radical. You're choosing to stop. Not because the world has paused around you, but because you've decided that this moment deserves your full attention. Let your body settle wherever it is. Feel the weight of your hands resting. Feel the gentle pull of gravity holding you to the earth. You don't need to fix your posture or arrange yourself perfectly. Just stop. Let the momentum of your day slow, the way a wheel gradually comes to rest. You've been moving so fast. Here, now, you don't have to move at all.`,

        `Notice what happens in the stillness. Your mind may still be spinning, replaying conversations, planning what comes next. That's okay. You haven't failed at pausing just because thoughts continue. The pause isn't the absence of thought. It's the decision to stop feeding the urgency. Feel your breath moving in and out without any effort on your part. Your body knows how to breathe. It's been doing it your whole life without your help. Can you trust it now? Can you let the breath simply happen while you rest in the watching? Notice what it feels like to want nothing, to need nothing, just for these few minutes.`,

        `Gently, begin to notice the space around you again. The sounds, the temperature, the quality of light even behind your closed eyes. You've just given yourself something rare, a moment of true stopping. It may have felt small, but this kind of pause sends ripples through your whole being. Your nervous system has been listening. Your body has been receiving. As you prepare to open your eyes, carry this feeling with you. You can always return to the pause. It's not something you have to create. It's what's already here when you stop looking for something else.`,
      ],
    },

    "Anchoring in Breath": {
      // 15 min — 4 segments
      segments: [
        `Welcome to this practice of anchoring in breath. Take a moment to arrive here, letting your eyes close or soften their gaze. Your breath has been with you since the very first moment of your life, and it will be with you until the very last. It's the most faithful companion you've ever known, yet we so rarely pay it any attention. Today, we're going to change that. Not by controlling the breath or trying to make it deeper or slower, but simply by turning toward it the way you'd turn toward a friend who's been waiting patiently for you to notice them. Let your awareness settle on the sensation of breathing, wherever you feel it most clearly.`,

        `Perhaps you feel the breath at the nostrils, a cool stream flowing in and warm air flowing out. Or maybe you notice it more in the rise and fall of your chest, or the gentle expansion and release of your belly. Wherever you find it, rest your attention there like a hand resting on a table. Lightly. Without gripping. When your mind wanders, and it will, that's not a problem. That's the practice. Each time you notice you've drifted, you're waking up. You're choosing presence again. Gently return to the breath. No frustration. No judgment. Just a quiet coming back, over and over.`,

        `Now let your awareness widen slightly to include the whole body breathing. Not just the nose or the belly, but the entire organism, expanding and contracting with each cycle. Notice how the breath moves through you like a wave. There's a moment at the top of each inhale where everything pauses, and a moment at the bottom of each exhale where everything empties. Rest in those turning points. They're tiny doorways into stillness. Your breath isn't just air moving in and out. It's your body's conversation with the world, taking in and letting go, receiving and releasing, thousands of times each day.`,

        `As we bring this practice to a close, notice how you feel right now compared to when we began. Perhaps there's a little more spaciousness. Perhaps the edges have softened. Your breath will continue after you open your eyes, of course. But now you know how to find it, how to anchor yourself in its steady rhythm when the world feels chaotic. You can return to this anchor in the middle of a meeting, stuck in traffic, lying awake at three in the morning. One conscious breath is all it takes to come home. Take one more deep, intentional breath now. Let it fill you completely. And as you exhale, gently open your eyes, returning to the world with this anchor still alive inside you.`,
      ],
    },

    "Body as Home": {
      // 15 min — 4 segments
      segments: [
        `Welcome to this practice of returning home to your body. Find a position that feels supportive and let your eyes gently close. For so many of us, the body has become something we manage rather than something we inhabit. We feed it, exercise it, dress it, but we rarely just live in it. We spend most of our time in the theater of the mind, running simulations, worrying, remembering. Today is an invitation to come back downstairs, to step out of the mind and into the body that's been holding you faithfully all along. Start by simply feeling the fact that you have a body. Feel its weight. Feel it breathing. Feel it being here.`,

        `Begin to move your attention slowly through your body, starting at the top of your head. Not looking for anything in particular, not trying to fix or relax anything, just visiting each region the way you'd walk through a home you haven't entered in a long time. The crown of your head. Your forehead, your temples. The muscles around your eyes, so often tight with concentration. Your jaw, which may be holding tension you didn't know was there. Let your awareness move at its own pace, without rushing. Your throat. Your shoulders. Notice if there's a story your shoulders are telling. Are they braced against something? Lifted toward your ears? Just notice. You don't have to change a thing.`,

        `Continue down through your arms and into your hands. Feel the aliveness in your fingertips, the subtle pulse of blood moving through them. Now bring your awareness into your chest and your heart space. There's often emotion stored here, things we've swallowed that we haven't fully digested. You don't need to name what you find, just acknowledge it. Move into your belly. This is where so many of us hold our deepest knowing and our deepest fear. Let the belly be soft. Let it move with the breath. Continue down through your hips, your legs, all the way to the soles of your feet. You've just traveled the full length of your home.`,

        `As we close this practice, take a moment to feel your body as a whole, a single living system, warm and breathing and present. This body has carried you through every experience you've ever had. It has healed its own wounds, fought off illness, adapted to every challenge. It deserves your attention and your kindness. You can return to this practice of body awareness anytime you feel disconnected or scattered. A few breaths of attention, a quick scan from head to feet, and you're home again. Begin to deepen your breath now. Wiggle your fingers and toes. When you open your eyes, see if you can maintain this feeling of being fully in your body, fully at home.`,
      ],
    },
  },

  // ── Retreat 2: "The Witnessing Eye" (Observation) ─────────────────

  "The Witnessing Eye": {
    "Watching Thoughts": {
      // 10 min — 3 segments
      segments: [
        `Welcome. Take a comfortable seat and let your eyes close. Today we're going to do something unusual. Instead of thinking, we're going to watch ourselves think. Most of the time, we're so caught up in our thoughts that we don't even realize we're thinking. It's like being inside a movie and forgetting we're in a theater. Right now, we're going to step back into the audience. We're going to watch the screen without climbing into the story. Take a few settling breaths and then simply open your attention to whatever thoughts arise. You don't have to invite them or push them away. They'll come on their own. They always do.`,

        `As you sit here, notice how thoughts appear. Do they arrive as words, as images, as feelings, or as some blend of all three? Notice that you didn't choose most of them. They simply appeared, like guests arriving at a party you didn't plan. And watch how each thought tries to pull you in, to convince you that it's important, that you need to follow it. You don't. You can let it pass. Imagine each thought as a leaf floating on a stream. You're sitting on the bank, watching. You're not the leaf. You're not even the stream. You're the one who sees. When you realize you've been swept downstream with a thought, don't be hard on yourself. Smile. And return to the bank.`,

        `Gently bring this practice to a close. You may have noticed something remarkable, that there is a part of you that can watch your thoughts without being them. This is your awareness, the silent witness that's always been here behind the noise. It doesn't judge. It doesn't react. It simply sees. This is a powerful discovery, because it means you're never truly trapped by any thought. You always have the option of stepping back and watching. Take a slow, grounding breath. Feel the surface beneath you. As you open your eyes, carry this witnessing quality with you. The next time a thought tries to sweep you away, remember that you can always return to the bank of the stream.`,
      ],
    },

    "Emotional Weather": {
      // 15 min — 4 segments
      segments: [
        `Welcome to this practice of emotional weather. Settle in comfortably and let your eyes close. We tend to think of emotions as facts, as definitive statements about reality. I'm angry, and therefore something is wrong. I'm sad, and therefore something has been lost. But what if emotions were more like weather? Weather passes through the sky but doesn't change the sky. The sky doesn't become the storm. It holds the storm. Today, we're going to practice being the sky. Take a few deep breaths, and as you settle, notice what emotional weather is present in you right now. Don't try to change it. Don't label it good or bad. Just notice the atmospheric conditions of your inner world.`,

        `Whatever you're feeling right now, see if you can get curious about it instead of reactive. Where in your body does this emotion live? Does it have a shape, a color, a temperature, a texture? Is it still, or is it moving? Some emotions feel like a tight knot in the chest. Others feel like a heaviness in the belly or a buzzing in the hands. You don't need to figure out why the emotion is there. You don't need to trace it to its source or solve the problem it points to. Right now, the only practice is to be present with it without trying to make it go away, and without getting lost in the story it's trying to tell you. Just feel it as sensation. Just let it be weather.`,

        `Notice how the emotion changes as you pay attention to it. It may intensify at first, the way a storm sometimes strengthens before it passes. That's okay. It may soften. It may shift into something else entirely. This is the nature of emotional weather: it's always moving, always changing. No feeling state is permanent, even though our minds try to convince us otherwise. The grief will last forever, the anxiety will never end. But your own experience tells you this isn't true. Think of the strongest emotion you felt last week. Where is it now? It passed. Whatever you're feeling right now will pass too. Not because you forced it, but because that's what weather does.`,

        `As we close this practice, take a moment to appreciate your own capacity to hold emotional weather without being destroyed by it. You've weathered every storm in your life so far, every one. And you're still here. Stronger, perhaps, for having let those storms move through rather than resisting them. As you return to your day, see if you can maintain this sky-like quality of awareness. When an emotion arises, notice it. Name it if that helps. And remember that you are not the weather. You are the vast sky that holds it all. Take a deep breath in. Release it slowly. Open your eyes when you're ready, carrying this spaciousness with you.`,
      ],
    },

    "Non-Judgment": {
      // 15 min — 4 segments
      segments: [
        `Welcome. Settle into stillness and let your eyes gently close. We spend an extraordinary amount of energy every day judging our experience. This is good, that is bad. I should be further along. I shouldn't feel this way. These judgments happen so fast and so automatically that we barely notice them. But they shape everything, how we see ourselves, how we relate to others, how we experience each moment. Today, we're practicing something radical: seeing without evaluating. Not good, not bad. Just this. Take a few breaths and begin to notice whatever is present in your awareness right now, sensation, thought, emotion, and practice meeting it with a simple acknowledgment. Ah, this is here.`,

        `As you sit, notice how quickly the judging mind activates. You might find yourself thinking this meditation is going well, or it's not going well. You might notice discomfort in your body and automatically label it as bad, as a problem to solve. This is the habit of a lifetime, and we're not going to break it in fifteen minutes. But we can loosen its grip. Each time you notice a judgment arising, gently label it. Judging. That's all. Don't judge yourself for judging. That would just be another layer of the same pattern. Just notice it, name it softly, and return to bare awareness. What is actually here, before your mind adds its commentary?`,

        `There's a profound freedom in non-judgment, and you may start to taste it even in these quiet minutes. When you stop needing your experience to be different from what it is, something relaxes at a very deep level. The constant effort of evaluation, of sorting everything into good and bad, wanted and unwanted, that effort is exhausting. And it doesn't actually change anything. The moment is already what it is by the time you judge it. Non-judgment isn't passivity or indifference. It's actually a deeper kind of seeing. When you stop labeling, you start perceiving more clearly. The raw experience beneath all our opinions is richer, stranger, and more alive than any judgment can capture.`,

        `As we draw this practice to a close, take a moment to notice how you feel right now. And before the judging mind rushes in to evaluate that feeling, just let it be. You are practicing one of the most challenging and most liberating skills in the human repertoire: the ability to let things be as they are. This doesn't mean you won't take action in your life or work to change what needs changing. It means that your actions will come from clarity rather than reactivity, from seeing rather than from judging. Take a deep breath in. As you exhale, let go of any residual effort. When you open your eyes, see if you can carry this quality of non-judgment into the next hour of your life. Just this. Just what is.`,
      ],
    },

    "Spacious Awareness": {
      // 20 min — 5 segments
      segments: [
        `Welcome to this practice of spacious awareness. Find a comfortable position, one where your body can be both relaxed and alert, and let your eyes gently close. For most of our lives, awareness is like a flashlight. We point it at one thing at a time, a thought, a problem, a sensation, and everything else fades into the background. Today, we're going to practice a different kind of awareness, one that's more like the sky than a flashlight. Vast. Open. Holding everything without grasping anything. Start by taking three slow, full breaths. With each exhale, imagine your awareness gently expanding outward, like a circle of light growing wider and wider.`,

        `Begin by noticing whatever is most prominent in your experience right now, the sound that's loudest, the sensation that's strongest, the thought that's most persistent. Acknowledge it. And then, gently, let your attention widen to include what else is here. The quieter sounds behind the loud one. The subtler sensations alongside the strong one. The space around the thought. You don't have to track everything. You're not trying to be aware of all things simultaneously. You're simply loosening the grip of your focus, letting awareness be more panoramic. Imagine you've been looking through a keyhole your whole life, and now you're opening the door.`,

        `As your awareness expands, you might notice something surprising: there's more space in your experience than there are objects. More silence than sound. More stillness than movement. More space between thoughts than thoughts themselves. We tend to focus on the contents of awareness, the thoughts, the feelings, the sensations, because they're vivid and demanding. But what about the space that holds them? That space is awareness itself. It was never absent. You just weren't noticing it, the way you don't notice the screen behind the movie because you're so engrossed in the story. Rest in that space now. Let it hold everything without you needing to manage anything.`,

        `From this spacious awareness, notice how different your experience feels compared to your normal focused, problem-solving mode. There may be a sense of ease, of being able to hold more, of not needing things to be different. Pain might still be present, but it's held in something larger. Worry might still surface, but it doesn't fill the entire space anymore. This is what the meditation traditions call the natural state, awareness that isn't constricted by the effort of controlling experience. You don't have to create this spaciousness. It's already here. You just have to stop narrowing it. Let your breath be effortless. Let your body be held by the ground beneath you. Let your mind be as wide as the sky.`,

        `Slowly, gently, allow the edges of your awareness to soften back toward the body. You don't have to collapse the spaciousness. You're simply reconnecting with the physical, the specific, while keeping that wide-open quality alive. Feel your hands. Feel your feet on the ground. Feel the breath in your chest. You've just spent time in a place that's always accessible to you, the open, unstructured awareness that exists before you narrow it into focus. You can return here any time you feel overwhelmed, contracted, or trapped. Three breaths and a willingness to let go of control, that's all it takes. Begin to move your fingers and toes. When you open your eyes, let the world enter that spacious awareness rather than snapping back to the flashlight. Wide. Open. Here.`,
      ],
    },
  },

  // ── Retreat 3: "Impermanence" (Change & loss) ─────────────────────

  Impermanence: {
    "What Is Passing": {
      // 15 min — 4 segments
      segments: [
        `Welcome. Let your body settle and your eyes close. Today we're turning our attention toward something we usually avoid: what is passing. Not just the big endings, but the quiet, ongoing departures that happen all the time. The season that's shifting. The age you'll never be again. The version of yourself that existed this morning, already gone. We resist looking at this because it frightens us. But there's something that happens when you face impermanence directly. It doesn't destroy you. It wakes you up. Take a few breaths and allow yourself to arrive in this moment, knowing that even this moment is already passing.`,

        `Bring to mind something in your life that is naturally coming to an end or changing. It might be a phase of life, a relationship that's evolving, a role you've been filling that no longer fits. Don't force anything, just see what surfaces. Notice how it feels in your body to sit with this awareness. There might be tightness in your chest, a heaviness in your belly, a sting behind your eyes. Let whatever is there be there. You don't have to manage it or make sense of it. In the Buddhist tradition, they say that to live fully, you must be willing to die continuously, to let each moment pass without clinging to it. This isn't morbid. It's the doorway to real presence.`,

        `Now notice something subtler. Even within this meditation, everything is passing. Each breath arises and dissolves. Each thought appears and vanishes. Sounds emerge and fade. Your body sensations are constantly shifting. Nothing stays. This isn't a philosophical concept. It's your direct experience, right now, in real time. You are sitting inside impermanence. It's not somewhere out there in the future. It's the texture of this very moment. See if you can rest in that flow without trying to hold anything in place. Let each moment arrive fully and depart fully, like waves on a shore. Nothing to clutch. Nothing to push away. Just the endless, tender procession of now.`,

        `As we close this practice, take a moment to acknowledge whatever arose for you. You've done something brave today. You've looked at what's passing instead of pretending it's permanent. And in doing so, you may have discovered something paradoxical: there's a kind of peace in letting go. Not a happy peace, necessarily, but a true one. The peace of alignment with how things actually are. As you return to your day, carry this gentle awareness with you. Notice the small departures, the last sip of tea, the light shifting on the wall, the moment between this breath and the next. Each one is precious precisely because it won't come again. Open your eyes when you're ready, arriving once more in a world that is always, beautifully, passing.`,
      ],
    },

    "Grief and Release": {
      // 20 min — 5 segments
      segments: [
        `Welcome to this practice of grief and release. Settle into your body, finding a position where you feel both safe and present. Let your eyes close. We carry so much grief that we don't call grief. It's not always about death. It's the friend who moved away. The version of your child who no longer exists. The dream you quietly let go of. The person you used to be. These losses accumulate in the body and the heart, often unacknowledged because they seem too small to grieve. But grief doesn't care about scale. It simply asks to be felt. Today, we're making space for whatever grief lives in you, large or small, old or fresh. You don't have to do anything with it. Just let it know it's welcome here.`,

        `Begin with your breath. Let it be slow and unhurried. With each inhale, imagine you're breathing into the place where grief lives in your body. You may already know where that is. For many people, it's the chest, a heaviness or an ache behind the breastbone. For others, it's the throat, tightened around words that were never spoken. For some, it's the belly, holding the weight of what's been swallowed. If you're not sure where your grief lives, just breathe normally and wait. The body will show you. It always does, when you give it permission and time. Whatever surfaces, breathe into it. Not to fix it. Just to say, I see you. I'm here.`,

        `Now, if you're willing, allow a specific loss to come to mind. It doesn't have to be the biggest one. Sometimes the smaller griefs are the ones most in need of attention because we've told ourselves they don't matter. Hold this loss gently in your awareness. Don't replay the whole story, just feel the essence of what was lost. What did it mean to you? What space did it fill that's now empty? Allow any feelings to arise without judgment: sadness, anger, regret, relief, confusion. Grief isn't neat. It doesn't follow rules. Whatever you feel is the right thing to feel. Let the tears come if they come. Let the stillness stay if it stays.`,

        `Now we practice release. Not letting go of the love or the meaning, but releasing the grip of holding on so tightly. Imagine that with each exhale, you're gently opening your hands around this loss. You're not throwing it away. You're allowing it to exist without needing to clutch it. There's a difference between honoring what was and using grief to stay tethered to the past. You can carry someone in your heart without carrying them on your back. You can remember a lost dream without punishing yourself for its absence. Breathe out and soften your hold. Breathe in and let tenderness fill the space that opens.`,

        `As we bring this practice to a close, place a hand on your heart if that feels right. Feel the warmth of your own palm, the steady beat beneath it. You've just done some of the most courageous work a human being can do: you've turned toward your grief instead of away from it. Whatever arose, it was enough. Whatever you felt, it was valid. Grief is not a problem to be solved. It's love with nowhere to go, and making space for it is one of the most compassionate things you can do for yourself. Take a few gentle breaths. Begin to notice the room around you. When you open your eyes, do so slowly, as if waking from a deep and necessary rest. The world is still here. And so are you.`,
      ],
    },

    "The Beauty of Transience": {
      // 20 min — 5 segments
      segments: [
        `Welcome. Let yourself settle and close your eyes. In Japanese culture, there's a concept called mono no aware, a gentle sadness at the passing of things. It's the feeling you get watching cherry blossoms fall, knowing they bloom for just a few days. But here's what's remarkable: the brevity is not despite the beauty. It is the beauty. If cherry blossoms lasted all year, nobody would make a pilgrimage to see them. Today, we're going to explore this paradox, that impermanence is not the enemy of meaning but its deepest source. Take a slow breath in, and as you exhale, let yourself arrive fully in this unrepeatable moment.`,

        `Bring to mind something beautiful that didn't last. A sunset you witnessed. A perfect afternoon with someone you love. A period of your life that shines in memory. Don't replay it like a film. Just feel the warmth of it. Notice how the beauty and the transience are woven together. Would that sunset have pierced you the way it did if it had lasted for hours? Would that afternoon carry such tenderness in memory if you could replay it anytime you wanted? The ache you feel when you remember something beautiful that's gone, that ache is not a mistake. It's your heart recognizing what matters. It's the proof that you were paying attention. Stay with that feeling. Let it be as complex as it is, beautiful and sad and grateful all at once.`,

        `Now turn your attention to something present in your life right now that won't last forever. Your health. A friendship. Your child's age. The city you live in. Whatever comes to mind, hold it with the awareness that it is temporary. Notice what happens in your body when you do this. There may be a tightening, a resistance. That's your mind trying to deny impermanence. But beneath the resistance, there may also be a deepening of appreciation, a brightening of attention. This is the gift of transience. When you really, truly know that something won't last, you stop sleepwalking through it. You stop saving your presence for some future moment. You arrive here, where the actual living is happening.`,

        `Notice your breath again. Each breath is a perfect example of transience. Each one arises, fills you, and dissolves. You'll never breathe this particular breath again. And yet you don't mourn each exhale. You trust the next inhale will come. There's a wisdom in that trust, a willingness to let each breath be complete in itself. What if you could live your whole life this way? Each day complete. Each experience whole. Not clinging to inhales or dreading exhales, but riding the rhythm of arising and passing with grace and wonder. This is what the contemplatives mean when they speak of being fully alive. Not holding on, not pushing away, just being present for the whole gorgeous, vanishing show.`,

        `As we close this practice, take a moment to feel gratitude for the fact that things end. Yes, gratitude. Because endings are what make meaning possible. A story with no ending isn't a story. A song that never resolves isn't a song. Your life derives its depth and beauty from the fact that it's finite, that every moment matters precisely because it won't come again. As you return to your day, carry this awareness lightly. Maybe pause a little longer at the window. Maybe really taste your next cup of tea. Maybe look at the people you love and let yourself feel how precious they are, not despite the fact that this won't last, but because of it. Open your eyes gently. The world is passing. And it is so beautiful.`,
      ],
    },

    "Finding Stillness in Flow": {
      // 20 min — 5 segments
      segments: [
        `Welcome. Settle into your seat, let your eyes close, and take a long, slow breath. Everything is moving. Your blood is circulating. Your cells are dividing. Your thoughts are streaming. The earth is spinning at a thousand miles an hour and hurtling through space at sixty-seven thousand more. There is nothing static anywhere in the universe. And yet, here you are, sitting still. Or are you? Today we explore a paradox that lies at the very heart of mindfulness: how to find the unmoving center within the ceaseless flow of change. Not by stopping the flow, that's impossible, but by discovering what was never moving in the first place.`,

        `Start with the most obvious movement: your breath. Watch it flow in and out. It never stops, never pauses for long. It's been flowing since you were born. Now notice the space between breaths. At the top of each inhale, there's a brief stillness. At the bottom of each exhale, another. These tiny gaps are doorways. Rest your attention in one of them. You don't have to hold your breath. Just notice the turning point, the place where inhalation becomes exhalation, where movement reverses direction. There's a stillness there that isn't the absence of movement. It's the axis around which movement happens. Like the hub of a wheel that remains still while the spokes spin around it.`,

        `Now expand your awareness to include your thoughts. They're flowing too, appearing and dissolving, one after another, a never-ending river. But what is it that notices the flow? What is it that sees one thought end and another begin? Whatever that is, it's not moving with the thoughts. It's the riverbank watching the water pass. It's the screen on which the images are projected, unchanged by any of them. Rest in that watching quality. You don't have to name it or understand it. Just notice that there's something in you that has never been swept away by any thought, any emotion, any experience. It's been here all along, still and clear, while everything else comes and goes.`,

        `Feel your body now, the sensations that are constantly shifting, itches, aches, warmth, coolness, tingling. Your body is a symphony of movement at every scale. And yet, within all of that movement, there's a felt sense of simply being here. Not being this sensation or that one, not being comfortable or uncomfortable, just being. This being-ness doesn't come and go. It was here when you were five years old, and it's here now. The contents have changed completely, your body, your thoughts, your entire life, but the fact of being aware, the simple presence of you, has remained constant. Can you feel that? The still point. The thing that doesn't change while everything else does.`,

        `As we close this practice, take a moment to rest in both realities at once, the flow and the stillness, the movement and the center. You don't have to choose between them. They coexist, always have. This is perhaps the deepest insight of the mindfulness tradition: that you are both the river and the riverbank, both the dance and the stillness from which the dance arises. As you return to the movement of your day, the tasks and conversations and decisions, know that the still point is always available to you. It doesn't require a meditation cushion or silence. It's here right now, in the middle of everything. Take a grounding breath. Feel your feet. Open your eyes. The world is flowing. And you are still. And both of those things are absolutely, perfectly true.`,
      ],
    },
  },

  // ── Retreat 4: "Compassion's Gate" (Heart practices) ──────────────

  "Compassion's Gate": {
    "Self-Compassion": {
      // 15 min — 4 segments
      segments: [
        `Welcome. Let your body settle into a comfortable position and close your eyes. Today we're going to practice something that many of us find surprisingly difficult: being kind to ourselves. We live in a culture that confuses self-compassion with self-indulgence, as if being gentle with yourself means lowering your standards. But research and centuries of contemplative practice tell us the opposite. Self-compassion doesn't make you weak. It makes you resilient. It gives you the inner safety to face hard truths without being crushed by them. So let's begin simply. Place a hand on your chest if that feels comfortable. Feel the warmth of your own touch. Feel your heartbeat. And silently acknowledge: this is a moment of difficulty, and I deserve kindness.`,

        `Think of someone you love, a child, a dear friend, a partner. Imagine they came to you in pain, telling you they'd failed at something, that they weren't good enough, that they were struggling. What would you say to them? Feel the tenderness that rises naturally when someone you love is hurting. The gentleness in your voice. The softness in your eyes. Now here's the practice: can you turn that same tenderness toward yourself? We almost never do this. When we're struggling, the inner voice gets harsh. You should have known better. What's wrong with you? Everyone else seems to manage. Notice if that voice is present right now. Notice its tone. And then, gently, replace it with the voice you'd use for someone you love.`,

        `Silently, offer yourself a few phrases of compassion. You might say: May I be kind to myself. May I accept myself as I am. May I forgive myself for what I cannot change. Let these words land in your body, not just in your mind. If resistance arises, that's normal. Self-compassion can feel vulnerable, even threatening, especially if you've spent years being your own harshest critic. The resistance isn't a sign that you're doing it wrong. It's a sign that you're touching something real. Stay with it. Breathe into the places that feel tight or defended. You don't have to force anything open. Just let the warmth of your own attention rest on those places, the way sunlight rests on closed petals. They'll open when they're ready.`,

        `As we bring this practice to a close, know that self-compassion isn't a one-time event. It's a practice, meaning you'll need to come back to it again and again, especially when you least feel you deserve it. That's actually when you need it most. The goal isn't to feel good all the time. It's to meet yourself with kindness in all conditions, in failure and in success, in strength and in struggle. Take a deep breath. Feel the weight of your hand on your chest. You've just offered yourself something precious, something that changes the whole quality of your inner life when practiced consistently. When you open your eyes, carry this kindness with you. Not as a concept, but as a felt warmth in the center of your chest.`,
      ],
    },

    "Empathy as Practice": {
      // 20 min — 5 segments
      segments: [
        `Welcome to this practice of empathy. Let your eyes close and take a few settling breaths. Empathy is often described as putting yourself in someone else's shoes, but it's deeper than that. True empathy isn't imagining what you would feel in their situation. It's trying to understand what they feel, from within their experience, their history, their fears, their hopes. It requires a kind of surrender, a willingness to temporarily set aside your own perspective and enter someone else's world. This is not easy. Our own viewpoint is so loud, so constant, so convinced of its own correctness. But today, we practice. We soften the walls of self and let another's experience in.`,

        `Begin by thinking of someone close to you, someone whose life you know well. A partner, a sibling, a close friend. Picture them clearly. See their face, the way they hold their body, the expression they wear when they think no one is watching. Now imagine stepping behind their eyes. Not to judge their choices or solve their problems, but simply to feel what it's like to be them right now. What are they worried about? What are they hoping for? What do they carry that they haven't told anyone? You may not know the answers, and that's okay. The practice is in the reaching, the genuine attempt to feel your way into another's experience. Notice how your body responds as you do this. Does your chest soften? Does something open?`,

        `Now bring to mind someone you interact with regularly but don't know deeply. A coworker, a neighbor, someone you see at the market. Again, picture them. Consider that they have an entire inner world as rich and complicated as yours. They have childhood memories that shaped them, fears that keep them awake, moments of private joy that no one else knows about. They've cried alone. They've laughed so hard they couldn't breathe. They've been afraid. They've been brave. Every person you pass on the street is carrying this kind of depth. Let that realization wash over you. It's humbling and it's connecting. When you truly feel the fullness of another person's humanity, something changes in how you relate to them.`,

        `Finally, and this is the most challenging step, bring to mind someone you find difficult. Not someone who's harmed you deeply, just someone who irritates you, who you disagree with, whose behavior you don't understand. Can you, even for a moment, wonder what the world looks like from inside their experience? What pain might be driving the behavior you find so difficult? What fear might be underneath their aggression or their withdrawal? You don't have to approve of their actions. Empathy isn't agreement. It's understanding. And understanding doesn't weaken your position. It deepens it. Notice if your body resists this exercise. That resistance is honest information. Don't force it. Just notice it and breathe.`,

        `As we close, take a moment to reconnect with yourself. Place your hand on your heart and feel your own breathing. You've just stretched the boundaries of your awareness to include the inner lives of others, and that is no small thing. Empathy is a muscle. The more you practice it, the stronger it gets, and the more naturally it arises in your daily interactions. You'll find yourself listening differently, seeing people for who they are beneath the surface. Take a deep breath. Let your awareness return to your own body, your own space. When you open your eyes, carry this expanded awareness with you. The world is full of people who are just as real as you are. Let that truth change how you move through your day.`,
      ],
    },

    Forgiveness: {
      // 20 min — 5 segments
      segments: [
        `Welcome. Find a position that feels safe and supported. Let your eyes close. Forgiveness is one of the most misunderstood practices in the contemplative traditions. It is not condoning. It is not forgetting. It is not pretending that what happened was acceptable. Forgiveness is the decision to set down a burden you've been carrying, not for the sake of the person who hurt you, but for your own freedom. Resentment is like drinking poison and waiting for the other person to get ill. It binds you to the very thing you want to be free of. Today, we're going to explore what it might feel like to begin loosening that grip. Not all at once. Not completely. Just enough to feel the first breath of freedom.`,

        `Start with your body. When you think of the person or situation you're carrying resentment toward, where do you feel it physically? Is there tightness in your jaw, your shoulders, your belly? Is there heat in your chest? Resentment lives in the body as much as in the mind. It takes a physical toll, muscle tension, disrupted sleep, elevated stress hormones. Your body has been holding this for you, standing guard, keeping the pain close in case you need it as armor. Acknowledge that. Thank your body for trying to protect you. And then ask, gently: is this weight still serving me? Is holding on still keeping me safe? Or has the holding itself become the heaviest thing I'm carrying?`,

        `Now, if you're willing, bring to mind the person or situation. You don't need to replay the whole story. Just hold the essence of it. And try, as an experiment, to see the other person not just as the one who hurt you, but as a full human being, flawed and struggling, acting from their own pain and limitation. This does not excuse what they did. Let me say that again: understanding is not excusing. But when you can see the whole person, not just the wound they inflicted, something shifts. The story becomes slightly less absolute. The grip loosens by a fraction. If this is too much right now, that's completely fine. Return to your breath. Forgiveness has its own timeline, and forcing it creates more harm.`,

        `The most important forgiveness is often the forgiveness we owe ourselves. For not speaking up. For staying too long. For not knowing better. For being human. Can you turn toward yourself with the same willingness you might offer another? Silently say: I forgive myself for carrying this so long. I forgive myself for not being perfect. I forgive myself for the ways I've judged and punished myself. Feel how those words land in your body. There may be tears. There may be relief. There may be numbness. Whatever arises is exactly right. This is tender work, and there's no timeline for completion. What matters is that you showed up today, that you were willing to look.`,

        `As we bring this practice to a close, know that forgiveness is not a single event. It's a direction you turn toward, again and again, each time you notice you've picked the burden back up. And you will pick it back up. That's human. The practice isn't in achieving permanent forgiveness. It's in the repeated choosing to set the weight down. Each time you choose release over resentment, you're a little freer. Take a deep breath. Feel the ground beneath you. Place your hand on your heart and feel its steady rhythm, the heart that has been brave enough to feel everything and keep beating. When you open your eyes, step gently into the world. Let yourself be tender for the rest of the day.`,
      ],
    },

    "Loving-Kindness": {
      // 30 min — 6 segments
      segments: [
        `Welcome to this practice of loving-kindness, known in the Pali language as metta. It is one of the oldest and most beautiful practices in the contemplative traditions, a systematic cultivation of unconditional goodwill that begins with yourself and radiates outward in ever-widening circles. Find a comfortable position. Let your eyes close. Take several slow breaths, letting each exhale soften your body a little more. We're going to spend this time deliberately generating warmth and care, not as a forced emotion but as an intention, a direction of the heart. Even if the feelings don't arise immediately, the intention itself is the practice. You're training the heart the way you'd train a muscle. Gently. Repeatedly. With patience.`,

        `We begin with ourselves, because you cannot genuinely offer others what you haven't first given to yourself. Place your hand on your chest and feel the warmth there. Silently, repeat these phrases, letting each one land in your body before moving to the next. May I be happy. May I be healthy. May I be safe. May I live with ease. Don't rush. Let the words be slow and sincere. If your mind resists, that's okay. You're not demanding that you feel happy or safe right now. You're expressing a wish for yourself, the same wish any loving parent would hold for their child. You deserve this goodwill. Not because you've earned it, but because you exist. Say it again. May I be happy. May I be healthy. May I be safe. May I live with ease.`,

        `Now bring to mind someone you love, someone whose face makes you smile just thinking of them. A partner, a child, a dear friend, even a beloved pet. See them clearly. Feel the natural warmth that arises. And direct the same phrases toward them. May you be happy. May you be healthy. May you be safe. May you live with ease. Notice how much easier this might feel than directing it toward yourself. Let that warmth flow freely. You don't have to ration kindness. The heart's capacity for love is not a limited resource. The more you give, the more there is. Stay with this person for a while. Let the metta pour toward them like sunlight. Feel it in your chest, in your hands, in the softening of your face.`,

        `Now expand the circle to someone neutral, a person you see regularly but don't have strong feelings about. The barista who makes your coffee. The person who delivers your mail. Someone you pass on your daily walk. Bring them to mind and recognize that they, too, are a complete human being with hopes, fears, sorrows, and joys. They want to be happy, just like you. They want to be safe, just like you. Offer them the same phrases. May you be happy. May you be healthy. May you be safe. May you live with ease. This is where the practice gets interesting, because you're generating goodwill not from emotional attachment but from pure intention. You're choosing kindness toward someone you have no reason to love, and that choice is profoundly powerful.`,

        `Now, if you're willing, bring to mind someone you find difficult. Not the most difficult person in your life, start smaller. Someone who frustrates or annoys you. Recognize that this person, too, suffers. They, too, want to be happy and often go about it in unskillful ways, just as we all do. This is not about approving of their behavior. It's about recognizing their shared humanity and choosing not to close your heart. Offer the phrases. May you be happy. May you be healthy. May you be safe. May you live with ease. If this feels impossible, that's completely okay. Just the willingness to try is enough. Let the metta be imperfect. Let it be small. Even a tiny crack in the wall of resentment lets light in.`,

        `Finally, let the circle of loving-kindness expand to include all beings everywhere. Every person on every continent, in every home, hospital, and prison. Every creature in every forest, ocean, and sky. The whole living world. Hold them all in this warm intention. May all beings be happy. May all beings be healthy. May all beings be safe. May all beings live with ease. Feel the vastness of that wish. You don't have to make it happen. You just have to mean it. And in meaning it, you change the quality of your own consciousness. You become a person who walks through the world wishing others well. Take a slow, deep breath. Feel the warmth in your chest. When you open your eyes, carry this metta with you like a lamp.`,
      ],
    },
  },

  // ── Retreat 5: "Beginner's Mind" (Fresh seeing) ───────────────────

  "Beginner's Mind": {
    Unknowing: {
      // 20 min — 5 segments
      segments: [
        `Welcome. Let your eyes close and your body settle. Zen teacher Shunryu Suzuki once said, in the beginner's mind there are many possibilities, but in the expert's mind there are few. We spend so much of our lives accumulating knowledge, building frameworks, developing opinions. And all of that has value. But it comes with a hidden cost: the more we think we know, the less we actually see. Our certainties become filters, letting in only what confirms what we already believe. Today, we practice the art of unknowing, of deliberately setting aside our expertise and meeting experience fresh. Take a breath and, as you exhale, imagine setting down a heavy backpack labeled "Everything I'm Sure About."`,

        `Notice what's happening in your mind right now. There's probably a running commentary, labeling, categorizing, evaluating. That sound is a car. This sensation is my knee. I'm doing this meditation wrong, or right. These labels are so automatic we don't even notice them, but they insert a layer between us and direct experience. For the next few minutes, try something radical: meet each sensation, each sound, each thought, as if you've never encountered anything like it before. What is this experience of breathing, really, when you drop the word "breathing" and just feel it? What is this thing called sound when you don't name its source? It's strange and wonderful when you really look. The world becomes a place of mystery again.`,

        `Notice how uncomfortable the mind gets when it can't categorize things. Not knowing feels unstable, even threatening, to a mind that's built for pattern recognition and prediction. But sit with that discomfort for a moment. What if not knowing isn't a problem to be solved but a space to be explored? What if the most interesting things in life exist in the territory of uncertainty? Every genuine discovery, every real insight, every moment of creative breakthrough happens in the space of not knowing. The known is where we rest. The unknown is where we grow. You're sitting in that growth space right now. Let it be uncomfortable. Let it be alive. Let it be exactly what it is.`,

        `Now bring this quality of unknowing to something about yourself. Something you think you know for certain, a belief about who you are, what you're capable of, what you deserve. Just for this moment, hold it lightly. What if it's not true? Not necessarily false, just not as solid as you've assumed? What opens up when you loosen that certainty? You might feel vulnerable. You might feel excited. You might feel both. The self we think we know is often the self we stopped examining years ago. When was the last time you surprised yourself? When was the last time you did something that didn't fit your self-image? Unknowing the self isn't losing yourself. It's making room for the parts of you that your certainties have been keeping out.`,

        `As we close, take a moment to appreciate the courage it takes to sit in not knowing. The world rewards expertise, opinions, confidence. It rarely rewards the humble acknowledgment that we might be wrong, that there might be more to learn. But this is where wisdom lives, not in what we know, but in our relationship with what we don't. As you open your eyes, see if you can maintain this quality of fresh unknowing for even a few minutes. Look at your surroundings as if you've just arrived for the first time. Let things be strange again. Let them be wondrous. The moment you think you know what's going on, you've stopped paying attention. Stay curious. Stay open. Stay a beginner.`,
      ],
    },

    "Fresh Eyes": {
      // 20 min — 5 segments
      segments: [
        `Welcome. Close your eyes and settle in. Think about the last time you really looked at something. Not glanced at, not scanned for information, but truly looked. It's been a while, hasn't it? We stop seeing things once they become familiar. The brain is magnificently efficient: it categorizes, labels, and files away, and then it stops investing attention. That tree outside your window? Your brain stopped actually seeing it months ago. It just loads the file labeled "tree" and moves on. Today, we're going to interrupt that efficiency. We're going to practice seeing with fresh eyes, as if everything were being encountered for the very first time. Take a breath. And for just a moment, pretend you have no idea where you are or what anything is.`,

        `Keeping your eyes closed, bring your attention to the sensations of your body. But don't call them sensations. Don't call them anything. Just feel them as pure experience, as if you've never had a body before. What is this thing you're experiencing? There's warmth, pressure, tingling, pulsing. There's something rhythmic happening that you've always called breathing, but what is it really? Air moving through passages, a chest expanding and contracting, a whole system of exchange between your interior and the world outside. It's extraordinary when you actually pay attention. Your heart is beating right now without your permission. Something is keeping you alive, and you have no idea how it's doing it. Let wonder arise. Let the familiar become miraculous again.`,

        `Now turn your fresh eyes toward sound. Don't identify the sounds. Don't label them or trace them to their source. Just receive them as pure vibration entering your awareness. Some are continuous, some are punctuated. Some are close, some are far. Some are pleasant, some are harsh. But strip away the labels and they're all just patterns of vibration landing on your eardrums, being converted into electrical signals, somehow becoming what you experience as sound. How does that happen? Nobody really knows. Not fully. The fact that you can hear at all is a mystery wrapped in a miracle wrapped in something so ordinary that you've completely stopped appreciating it. Until now. Right now, just for a moment, let hearing be astonishing again.`,

        `Bring to mind someone you see every day. A partner, a housemate, a coworker. Someone so familiar that you've stopped really looking at them. Now imagine seeing them for the first time. Without the accumulated history, the small grievances, the habitual expectations. Just a human being in front of you, alive and breathing and as much a mystery as you are. What would you notice about them if you had no preconceptions? The color of their eyes? The way they hold their shoulders? The particular quality of their laugh? We take the people closest to us for granted more than anything else in our lives. Not out of cruelty, but out of familiarity. Fresh eyes is the antidote. It's a practice of re-seeing what we love before it's too late to see it at all.`,

        `As we bring this practice to a close, take one more breath with fresh eyes. Feel it as if it's the first breath you've ever taken. Notice the temperature of the air. The expansion of your ribs. The brief pause before the exhale. All of it, utterly unremarkable and utterly astonishing. The practice of fresh eyes isn't about forcing constant amazement. It's about loosening the grip of habit just enough to let reality back in. The world hasn't gotten less interesting since you were a child. You've just gotten more efficient at ignoring it. So as you open your eyes, take your time. Let the light enter. Let shapes and color register. This moment will never come again. See it. Really see it.`,
      ],
    },

    "The Ordinary Sacred": {
      // 30 min — 6 segments
      segments: [
        `Welcome to this practice, the final meditation on the Mindfulness path. We've traveled through presence, observation, impermanence, compassion, and fresh seeing, and now we arrive at the place where all of those threads converge: the recognition that the sacred is not somewhere else. It's here. In the ordinary, unremarkable, everyday moments you've been living all along. Let your body settle. Close your eyes. Take a breath. And know that this breath, this one, right now, is as sacred as any breath taken in any temple or monastery in the history of human seeking. Not because it's special. Because it's real. The sacred isn't something you have to go find. It's something you have to stop overlooking.`,

        `Think about your morning routine. The moment you open your eyes. The feeling of your feet touching the floor. Water running over your hands. The smell of coffee or tea. The first light through the window. We move through these moments on autopilot, rushing toward the "important" parts of the day. But what if these are the important parts? What if the sacred reveals itself most clearly in the moments we've decided are too mundane to notice? The Zen tradition teaches this directly: before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water. The activities don't change. The quality of attention changes. And that changes everything. Bring your morning to mind now, and see if you can find the sacredness in it.`,

        `The breath moving through you right now is the same force that moves wind through trees and tides across shorelines. Your heartbeat is made of the same rhythm that pulses through all living things. You're not separate from the natural world, sitting here in your room or your chair. You're part of it, a node in an unbroken web of life that stretches back billions of years. The atoms in your body were forged in dying stars. The water in your cells has been rain, river, ocean, cloud, and rain again, millions of times. This isn't poetry. This is chemistry. And it means that every ordinary moment of your existence is an expression of something vast and ancient and sacred beyond comprehension. Feel that in your body now. Feel the stardust. Feel the rain.`,

        `Now think about the people in your life. The ones you share meals with, sit in traffic with, pass in hallways. Each one is carrying a universe inside them, a complete cosmos of memory, hope, fear, love, confusion, and longing. Every interaction, no matter how brief, is a meeting of universes. The cashier at the grocery store. The stranger on the bus. Your own reflection in the mirror. All sacred. Not because of anything they've done or achieved, but because they exist at all. The probability of any single human being existing is so astronomically small that every person you've ever met is a statistical miracle. Including you. Let that settle into your bones. You are a statistical miracle, sitting here, breathing, aware.`,

        `We often think of spiritual practice as something separate from daily life. We meditate, and then we get up and go back to the "real world." But what if the meditation isn't the spiritual practice? What if the spiritual practice is the dishes? The commute? The difficult conversation? The Tuesday afternoon when nothing remarkable happens? The contemplatives who've gone deepest all seem to arrive at the same insight: the ordinary is the sacred in disguise. Or rather, the ordinary is the sacred without disguise, and we've been looking right through it, searching for something more impressive. The most profound thing you'll ever do might be sitting here right now, just breathing, just being aware. Just this. Just this.`,

        `As we close this practice, and with it this stretch of the Mindfulness path, feel everything we've explored. The pause. The breath. The body. Witnessing thoughts and emotions. Accepting impermanence. Opening the heart. Fresh eyes. And now, the ordinary sacred. These aren't separate skills. They're facets of a single way of being. You don't need a mountaintop. The sacred is in the creak of the floorboard under your feet. It's in the steam rising from your cup. It's in the sound of your own name spoken by someone who knows you. Take a long, full breath. When you open your eyes, you'll enter the same world you've always lived in, but you might see it differently. Not because it's changed, but because you have. Go gently. The sacred is everywhere. And you are part of it.`,
      ],
    },
  },
};
